name: janus_client
description: janus gateway client for dart
version: 0.0.4
homepage: https://github.com/shivanshtalwar0/flutter_janus_client
publish_to: 'none'

environment:
  sdk: ^2.12.0-0

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_webrtc:
    git: https://github.com/flutter-webrtc/flutter-webrtc.git
  net:
    git: https://github.com/lamtx/net.git
  path_provider: ^2.0.1
  http: ^0.13.0
  web_socket_channel: ^2.0.0
  stream_channel: ^2.1.0
  uuid: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.4

flutter:
