name: janus_client
description: janus gateway client for dart
version: 0.0.4
homepage: https://github.com/shivanshtalwar0/flutter_janus_client
publish_to: 'none'

environment:
  sdk: ^2.12.0-0

dependencies:
  flutter_webrtc:
    git: https://github.com/flutter-webrtc/flutter-webrtc.git
  http: ^0.13.0
  net:
    git: https://github.com/lamtx/net.git
  stream_channel: ^2.1.0
  web_socket_channel: ^2.0.0

dev_dependencies:
  test: ^1.16.4